import { seo } from '@/data/seo';
import { site } from '@/data/site';

/** Absolute URL on the production domain (canonicals, Open Graph, schema). */
export const absoluteUrl = (route = '/') => (route === '/' ? `${site.url}/` : `${site.url}${route}`);

// Generated by src/app/opengraph-image.js. Setting openGraph/twitter per page replaces the file-based image on
// nested routes, so every page names it explicitly.
const shareImage = { url: '/opengraph-image', width: 1200, height: 630, alt: 'Logo Makers Pro: custom logo design services' };

/** Next.js metadata for a route: title, description, canonical, Open Graph and Twitter card. */
export function pageMetadata(route, overrides = {}) {
  const entry = seo[route] || {};
  const title = entry.title || site.name;
  const url = absoluteUrl(route);
  return {
    title,
    ...(entry.description ? { description: entry.description } : {}),
    alternates: { canonical: url },
    openGraph: {
      type: 'website',
      siteName: site.name,
      locale: 'en_US',
      url,
      title,
      ...(entry.description ? { description: entry.description } : {}),
      images: [shareImage],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      ...(entry.description ? { description: entry.description } : {}),
      images: [shareImage],
    },
    ...overrides,
  };
}
